### ISSUE TITLE
Cannot Run on Devices with Knox < 2.5

### ISSUE THREAD

**Issue by error454** [LayoutXML/SABS#40]
I have a Note 3 (API 21, Knox 2.3). I get the following error during app configuration:
`java.lang.NoSuchMethodError: No virtual methof getFirewall()Lcom/sec/enterprise/firewall/Firewlll;`

According to [this post](https://seap.samsung.com/forum-topic/works-some-tablets-not-others-knoxcontainermanagergetfirewall), the method was added in 2.5.

**Comment by my-password-is-password** [comment]
@error454 Does your SABS crash right after you try to open it?  I have a Galaxy S4 (Android 5.0.1, Knox 2.3) and I was able to install and open SABS v0.0.7 but it started crashing with v0.0.8 and v0.0.9.  I don't know if I'm having the same problem as you or if its something else.

Here's a gif of SABS crashing as soon as I click the icon.

![sabscrash](https://user-images.githubusercontent.com/6408935/37724317-b1a711be-2ced-11e8-9d27-977c651ae57b.gif)

**Comment by error454** [comment]
> @error454 Does your SABS crash right after you try to open it?
It crashes after going through the 5 tutorial tabs on a screen that looks like it's asking for the samsung dev key.

**Comment by my-password-is-password** [comment]
Ok.  I think its the same problem.  I didn't get the tutorial and the asking for the dev key because I installed over v0.0.7 and it saved the info.

**Comment by LayoutXML** [comment]
@error454, @my-password-is-password, it seems like I can't fix the issue. Have you used Adhell or Adhell 2 before? If yes, did it work? I have a feeling those apps never worked on knox 2.3 as well.

**Comment by my-password-is-password** [comment]
@LayoutXML Never tried either Adhell or Adhell 2 on the S4.  I reinstalled SABS v007 and added ```github.com``` to the blacklist then tried navigating to ```github.com``` in chromium and it blocked it.  So  it looks like v007 still works with Knox 2.3.

![sabs v007](https://user-images.githubusercontent.com/6408935/37866184-47e75e10-2f44-11e8-9af4-5fed8035ad86.gif)

**Comment by my-password-is-password** [comment]
@LayoutXML I was playing around with v007 again and I think that  ```github.com``` example in my other comment was a fluke because i tried again with ```google.com``` and I was able to load the page with no problem.  Just getting SABS to "turn on" seems like its ramdom.  It's probably not even worth to look into it.  Sorry if I wasted your time.
